---
title: "Benchmark"
author: '2053'
date: "2025-04-20"
output: html_document
---

```{r setup, include=FALSE}
# 1. Load reticulate
if (!requireNamespace("reticulate", quietly = TRUE)) {
  install.packages("reticulate")
}
library(reticulate)

# 2. Create the conda env if it doesn't exist
envs <- conda_list()$name
if (!"r-reticulate-conda" %in% envs) {
  conda_create(envname = "r-reticulate-conda",
               packages = c("python=3.8"))
}

# 3. Bind reticulate to that env
use_condaenv("r-reticulate-conda", required = TRUE)

# 4. Install Python packages via pip
#    - a local annoy wheel you downloaded
#    - scrublet from PyPI
conda_install(
  envname  = "r-reticulate-conda",
  packages = c("./wheel/annoy-1.17.0-cp38-cp38-win_amd64.whl"),
  pip      = TRUE
) # For Windows, annoy wheel needs to manually download for Scrublet.
conda_install(
  envname  = "r-reticulate-conda",
  packages = c("scrublet"),
  pip      = TRUE
)

# 5. Ensure BiocManager is available
if (!requireNamespace("BiocManager", quietly = TRUE)) {
  install.packages("BiocManager", repos = "https://cloud.r-project.org")
}

# 6. Install & load R packages one by one
if (!requireNamespace("SingleCellExperiment", quietly = TRUE)) {
  BiocManager::install("SingleCellExperiment", ask = FALSE, update = FALSE)
}
library(SingleCellExperiment)

if (!requireNamespace("scDblFinder", quietly = TRUE)) {
  BiocManager::install("scDblFinder", ask = FALSE, update = FALSE)
}
library(scDblFinder)

if (!requireNamespace("DoubletCollection", quietly = TRUE)) {
  remotes::install_github('https://github.com/ekernf01/DoubletFinder', force = T) # It is better to use version 2.0.3.
}
library(DoubletCollection)
```


```{r,warning=FALSE}
datasets <- list.files("datasets", pattern="\\.rds$", full=TRUE)
names(datasets) <- gsub("\\.rds$","",basename(datasets))
methods <- c('Scrublet','DoubletFinder','scDblFinder.clusters','scDblFinder.random')
# methods <- methods[-1]
datasets <- lapply(datasets, readRDS)

wrap <- function(x, method){
  switch(method,
      "DoubletFinder"=DoubletCollection:::CallDoubletFinder(x),
      "Scrublet"=DoubletCollection:::CallScrublet(x),
      "scDblFinder.clusters"=scDblFinder(x, clusters=TRUE)$scDblFinder.score,
      "scDblFinder.random"=scDblFinder(x, clusters=FALSE)$scDblFinder.score
    )
}

scores <- lapply(datasets, FUN=function(x){
  x <- x[[1]]
  lapply(setNames(methods, methods), FUN=function(method){
    tryCatch({
      # average across 2 seeds:
      set.seed(42)
      st1 <- system.time( sco1 <- wrap(x, method) )
      set.seed(1234)
      st2 <- system.time( sco2 <- wrap(x, method) )
      list(scores=c(sco1+sco2)/2, time=(st1+st2)/2)
    }, error=function(e){
      warning("Error running ", method,":\n", e)
      list(scores=rep(NA_real_, ncol(x)), st=NA)
    })
  })
})
saveRDS(scores, file="scores.rds")
```

```{r}
scores <- readRDS("scores.rds")
true_labels <- lapply(datasets, FUN=function(x) as.integer(x[[2]]=='doublet'))

res <- dplyr::bind_rows(lapply(setNames(names(scores),names(scores)), 
                               FUN=function(ds){
  truth <- true_labels[[ds]]
  dplyr::bind_rows(lapply(scores[[ds]], FUN=function(x){
    s <- split(x$scores, truth)
    c(AUPRC=mean(as.numeric(PRROC::pr.curve(s[[2]], s[[1]])[2:3])),
      AUROC=PRROC::roc.curve(s[[2]], s[[1]])[[2]],
      elapsed=as.numeric(unlist(x$time["elapsed"])))
  }), .id="method")
}), .id="dataset")
saveRDS(as.data.frame(res), file="benchmark.results.rds")
```
